awk '
/Vite middleware for development/ {
print "  app.post(\"/api/workouts/:id/mutate\", async (req, res) => {"
print "    try {"
print "      const idToken = req.headers.authorization?.split(\"Bearer \")[1];"
print "      if (!idToken) return res.status(401).json({ error: \"Unauthorized\" });"
print "      const decodedToken = await adminAuth.verifyIdToken(idToken);"
print "      const uid = decodedToken.uid;"
print ""
print "      const { id } = req.params;"
print "      const { baseVersion, updates, duration, volume } = req.body;"
print ""
print "      const dbId = firebaseConfig.firestoreDatabaseId || \"(default)\";"
print "      const docSnap = await fetchUserDoc(firebaseConfig.projectId, dbId, idToken, \"workouts\", id);"
print "      if (!docSnap) {"
print "        return res.status(404).json({ error: \"Workout not found\" });"
print "      }"
print ""
print "      if (docSnap.version !== baseVersion) {"
print "        return res.status(409).json({ error: \"Conflict: Stale version\", currentVersion: docSnap.version, workout: docSnap });"
print "      }"
print ""
print "      const updatedWorkout = {"
print "        ...docSnap,"
print "        ...updates,"
print "        duration: duration !== undefined ? duration : docSnap.duration,"
print "        volume: volume !== undefined ? volume : docSnap.volume,"
print "        version: docSnap.version + 1,"
print "        updatedAt: new Date().toISOString()"
print "      };"
print ""
print "      await updateDoc(firebaseConfig.projectId, dbId, idToken, \"workouts\", id, updatedWorkout);"
print ""
print "      res.json({ success: true, workout: updatedWorkout });"
print "    } catch (e: any) {"
print "      res.status(500).json({ error: e.message });"
print "    }"
print "  });"
print ""
}
{print}' server.ts > server_new.ts
mv server_new.ts server.ts
