import assert from 'node:assert/strict';
import { acknowledgeWorkout } from '../src/lib/workout-sync';

const entries = new Map<string, string>();
const storage = { getItem: (k: string) => entries.get(k) ?? null, setItem: (k: string, v: string) => entries.set(k, v), removeItem: (k: string) => entries.delete(k) };
Object.defineProperty(globalThis, 'localStorage', { value: storage, configurable: true });
Object.defineProperty(globalThis, 'window', { value: { localStorage: storage }, configurable: true });
storage.setItem('FORGE_GEMINI_API_KEY', 'synthetic-test-key');
const { useAuthStore } = await import('../src/store/useAuthStore');
const { useWorkoutStore } = await import('../src/store/useWorkoutStore');
const { useGeminiStore } = await import('../src/store/useGeminiStore');
const sent: any = { id: 'w', userId: 'A', title: 'Before', scheduledDate: '2026-09-13', status: 'IN_PROGRESS', version: 1, sets: [] };
storage.setItem('forge-active-workout-v2', JSON.stringify({ state: { activeWorkout: sent } }));
assert.equal(useWorkoutStore.getState().activeWorkout, null, 'Never hydrate before authentication');
useAuthStore.getState().setUser({ uid: 'A' });
assert.equal(useWorkoutStore.getState().activeWorkout?.userId, 'A');
assert.equal(storage.getItem('FORGE_GEMINI_API_KEY'), null);
useGeminiStore.getState().setApiKey('synthetic-memory-key');
useAuthStore.getState().setUser({ uid: 'B' });
assert.equal(useWorkoutStore.getState().activeWorkout, null);
assert.equal(useGeminiStore.getState().apiKey, null);
useAuthStore.getState().setUser({ uid: 'A' });
assert.equal(useWorkoutStore.getState().activeWorkout?.id, 'w');
const response = { ...sent, version: 2 };
assert.deepEqual(acknowledgeWorkout(sent, sent, response), response);
const edited = { ...sent, title: 'New local edit' };
assert.deepEqual(acknowledgeWorkout(edited, sent, response), { ...edited, version: 2 });
const other = { ...sent, userId: 'B' };
assert.equal(acknowledgeWorkout(other, sent, response), other);
assert.equal(acknowledgeWorkout(null, sent, response), null);
assert.ok(!JSON.stringify([...entries.values()]).includes('synthetic-memory-key'));
useAuthStore.getState().setUser(null);
assert.equal(useWorkoutStore.getState().activeWorkout, null);
console.log('PASS owner-scoped hydration, identity cleanup, memory-only key and delayed acknowledgement');
